#!/bin/sh

git reset --hard

./poole.py --build
echo "lollipop123Tunguska" | sudo -S cp -r output/* /var/www/
echo "lollipop123Tunguska" | sudo -S cp -r static/* /var/www/

host=`hostname`
/home/thomas/bin/notify "Deployed to ${host}"
