#!/bin/bash

if [ -z "$1" ]; then
    echo "No argument supplied"
    exit 1
fi

sdir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
dir=$(dirname "${1}")
video=$(basename -- "${1}")
ext="${video##*.}"
name="${video%.*}"
tmp="${name}_tmp.png"

cd "$dir"
ffmpeg -i $video -vf "select=eq(n\,0)" -n -update 1 -frames:v 1 $tmp 2> /dev/null
identify -ping -format '%w %h' $tmp
rm -rf "$tmp"
